name: scalable_flutter_app_starter
description: A scalable Flutter app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  go_router: ^11.1.3
  url_launcher: ^6.1.14
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  gap: ^3.0.1
  cloud_firestore: ^4.12.2
  freezed_annotation: ^2.4.1
  uni_links: ^0.5.1
  meta: ^1.9.1
  image_picker: ^1.0.4
  firebase_storage: ^11.4.1
  flutter_image_compress: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_test:
    sdk: flutter

flutter_intl:
  enabled: true
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
